# Generated by Django 4.0.3 on 2024-09-08 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emporium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('LastPlayed', models.DateField(default=django.utils.timezone.now)),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('Selected', models.BooleanField(default=False)),
                ('ThroneLevel', models.IntegerField(default=1)),
                ('CampaignWorld', models.IntegerField(default=1)),
                ('VaultGold', models.IntegerField(default=0)),
                ('VaultStone', models.IntegerField(default=0)),
                ('VaultGems', models.IntegerField(default=10)),
                ('DungeonCheck', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuildExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('SlotNo', models.IntegerField()),
                ('Level', models.IntegerField()),
                ('BaseType', models.TextField()),
                ('FullType', models.TextField()),
                ('Duration', models.TextField()),
                ('StartDate', models.DateTimeField(null=True)),
                ('Results', models.JSONField(null=True)),
                ('Claimed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuildStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('Heist', models.TextField()),
                ('ThroneLevel', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('RoomTypes', models.JSONField()),
                ('Background', models.TextField()),
                ('BackgroundBias', models.JSONField()),
                ('BaseRewards', models.JSONField()),
                ('RoomRewards', models.JSONField()),
                ('Assignments', models.JSONField()),
                ('StageRewards', models.JSONField(null=True)),
                ('ObstaclesR1', models.JSONField()),
                ('ObstaclesR2', models.JSONField(null=True)),
                ('ObstaclesR3', models.JSONField(null=True)),
                ('ObstaclesR4', models.JSONField(null=True)),
                ('ObstaclesR5', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Throne', models.IntegerField()),
                ('Name', models.TextField()),
                ('Slot', models.TextField()),
                ('MagicLv', models.IntegerField()),
                ('TotalLv', models.IntegerField()),
                ('Power', models.IntegerField()),
                ('Requirement', models.TextField(null=True)),
                ('Trait', models.TextField(null=True)),
                ('Skill', models.TextField(null=True)),
                ('Combat', models.TextField(null=True)),
                ('Magic', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MarketStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('ThroneLevel', models.IntegerField()),
                ('ResourceId', models.TextField()),
                ('StoreType', models.TextField()),
                ('RareProperties', models.JSONField(null=True)),
                ('Bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Description', models.TextField(null=True)),
                ('Level', models.IntegerField()),
                ('Placement', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThiefInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Class', models.TextField()),
                ('Stars', models.TextField()),
                ('BasePower', models.IntegerField()),
                ('Level', models.IntegerField(default=1)),
                ('Experience', models.IntegerField(default=0)),
                ('BaseAgi', models.IntegerField(default=0)),
                ('BaseCun', models.IntegerField(default=0)),
                ('BaseMig', models.IntegerField(default=0)),
                ('BaseEnd', models.IntegerField(default=0)),
                ('TrainedAgi', models.IntegerField(default=0)),
                ('TrainedCun', models.IntegerField(default=0)),
                ('TrainedMig', models.IntegerField(default=0)),
                ('TrainedEnd', models.IntegerField(default=0)),
                ('Power', models.IntegerField(null=True)),
                ('Agility', models.IntegerField(null=True)),
                ('Cunning', models.IntegerField(null=True)),
                ('Might', models.IntegerField(null=True)),
                ('Endurance', models.IntegerField(null=True)),
                ('Health', models.IntegerField(null=True)),
                ('Attack', models.IntegerField(null=True)),
                ('Damage', models.IntegerField(null=True)),
                ('Defense', models.IntegerField(null=True)),
                ('Sabotage', models.IntegerField(null=True)),
                ('Perceive', models.IntegerField(null=True)),
                ('Traverse', models.IntegerField(null=True)),
                ('Status', models.TextField(default='Ready')),
                ('CooldownExpire', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThiefUnlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThiefFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockablethief')),
            ],
        ),
    ]
