# Generated by Django 4.0.3 on 2023-12-29 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emporium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventoryDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('KeepLevel', models.IntegerField(default=1)),
                ('TotalPower', models.IntegerField(default=0)),
                ('VaultGold', models.IntegerField(default=0)),
                ('VaultGems', models.IntegerField(default=0)),
                ('Selected', models.BooleanField(default=False)),
                ('LastPlayed', models.DateField(default=django.utils.timezone.now)),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ThiefUnlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ThiefFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockablethief')),
            ],
        ),
        migrations.CreateModel(
            name='ThiefInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Class', models.TextField()),
                ('Stars', models.TextField()),
                ('BasePower', models.IntegerField()),
                ('Level', models.IntegerField(default=1)),
                ('Experience', models.IntegerField(default=0)),
                ('BaseAgi', models.IntegerField(default=0)),
                ('BaseCun', models.IntegerField(default=0)),
                ('BaseMig', models.IntegerField(default=0)),
                ('BaseEnd', models.IntegerField(default=0)),
                ('TrainedAgi', models.IntegerField(default=0)),
                ('TrainedCun', models.IntegerField(default=0)),
                ('TrainedMig', models.IntegerField(default=0)),
                ('TrainedEnd', models.IntegerField(default=0)),
                ('Power', models.IntegerField(null=True)),
                ('Agility', models.IntegerField(null=True)),
                ('Cunning', models.IntegerField(null=True)),
                ('Might', models.IntegerField(null=True)),
                ('Endurance', models.IntegerField(null=True)),
                ('Health', models.IntegerField(null=True)),
                ('Attack', models.IntegerField(null=True)),
                ('Damage', models.IntegerField(null=True)),
                ('Defense', models.IntegerField(null=True)),
                ('Sabotage', models.IntegerField(null=True)),
                ('Perceive', models.IntegerField(null=True)),
                ('Traverse', models.IntegerField(null=True)),
                ('Position', models.TextField(default='Available')),
                ('Wounds', models.IntegerField(null=True)),
                ('Cooldown', models.TextField(default='Ready')),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
        migrations.CreateModel(
            name='MagicMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventoryDate', models.DateField(default=django.utils.timezone.now)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ItemFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockableitem')),
                ('ThiefFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockablethief')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ItemFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockableitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot', models.TextField()),
                ('Name', models.TextField()),
                ('Level', models.IntegerField()),
                ('TotalLv', models.IntegerField()),
                ('Power', models.IntegerField()),
                ('Requirement', models.TextField(null=True)),
                ('Trait', models.TextField(null=True)),
                ('Skill', models.TextField(null=True)),
                ('Combat', models.TextField(null=True)),
                ('Magic', models.TextField(null=True)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ThiefFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.thiefinguild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StageNo', models.IntegerField()),
                ('StageDate', models.DateField(default=django.utils.timezone.now)),
                ('ObstaclesR1', models.TextField()),
                ('ObstaclesR2', models.TextField(null=True)),
                ('ObstaclesR3', models.TextField(null=True)),
                ('TypeR1', models.TextField(null=True)),
                ('TypeR2', models.TextField(null=True)),
                ('TypeR3', models.TextField(null=True)),
                ('CompleteR1', models.BooleanField(default=False)),
                ('CompleteR2', models.BooleanField(null=True)),
                ('CompleteR3', models.BooleanField(null=True)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildRamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StageNo', models.IntegerField()),
                ('StageDate', models.DateField(default=django.utils.timezone.now)),
                ('ObstaclesR1', models.TextField()),
                ('TypeR1', models.TextField(null=True)),
                ('CompleteR1', models.BooleanField(default=False)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InventoryDate', models.DateField(default=django.utils.timezone.now)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ItemFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockableitem')),
                ('ThiefFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockablethief')),
            ],
        ),
    ]
