# Generated by Django 4.0.3 on 2023-12-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminguild',
            name='Attack',
        ),
        migrations.RemoveField(
            model_name='iteminguild',
            name='Damage',
        ),
        migrations.RemoveField(
            model_name='iteminguild',
            name='Defense',
        ),
        migrations.AddField(
            model_name='iteminguild',
            name='Combat',
            field=models.TextField(null=True),
        ),
    ]
