# Generated by Django 4.0.3 on 2023-12-29 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emporium', '0001_initial'),
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='UserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonwares',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='commonwares',
            name='ItemFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockableitem'),
        ),
        migrations.AlterUniqueTogether(
            name='guild',
            unique_together={('UserFK', 'Name')},
        ),
    ]
