# Generated by Django 4.0.3 on 2024-09-08 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('emporium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thiefunlocked',
            name='UserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thiefinguild',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='roominguild',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='marketstore',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='itemunlocked',
            name='ItemFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emporium.unlockableitem'),
        ),
        migrations.AddField(
            model_name='itemunlocked',
            name='UserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminguild',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='iteminguild',
            name='ThiefFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.thiefinguild'),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='guildexpedition',
            name='GuildFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild'),
        ),
        migrations.AddField(
            model_name='guildexpedition',
            name='ThiefFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.thiefinguild'),
        ),
        migrations.AddField(
            model_name='guild',
            name='UserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='guild',
            unique_together={('UserFK', 'Name')},
        ),
    ]
