# Generated by Django 4.0.3 on 2024-10-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminguild',
            name='ThiefFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.thiefinguild'),
        ),
    ]
