# Generated by Django 4.0.3 on 2024-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_iteminguild_thieffk'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='LastHeist',
            field=models.TextField(default='tower'),
        ),
    ]
