# Generated by Django 4.0.3 on 2024-01-05 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_rename_stagedate_guildtower_createdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heist', models.TextField()),
                ('StageNo', models.IntegerField()),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('TypeR1', models.TextField()),
                ('TypeR2', models.TextField(null=True)),
                ('TypeR3', models.TextField(null=True)),
                ('TypeR4', models.TextField(null=True)),
                ('TypeR5', models.TextField(null=True)),
                ('ObstaclesR1', models.TextField()),
                ('ObstaclesR2', models.TextField(null=True)),
                ('ObstaclesR3', models.TextField(null=True)),
                ('ObstaclesR4', models.TextField(null=True)),
                ('ObstaclesR5', models.TextField(null=True)),
                ('CompleteR1', models.BooleanField(default=False)),
                ('CompleteR2', models.BooleanField(default=False)),
                ('CompleteR3', models.BooleanField(default=False)),
                ('CompleteR4', models.BooleanField(default=False)),
                ('CompleteR5', models.BooleanField(default=False)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
        migrations.RemoveField(
            model_name='guildassets',
            name='GuildFK',
        ),
        migrations.RemoveField(
            model_name='guildassets',
            name='ItemFK',
        ),
        migrations.RemoveField(
            model_name='guildassets',
            name='ThiefFK',
        ),
        migrations.RemoveField(
            model_name='guildramp',
            name='GuildFK',
        ),
        migrations.RemoveField(
            model_name='guildtower',
            name='GuildFK',
        ),
        migrations.RemoveField(
            model_name='magicmarket',
            name='GuildFK',
        ),
        migrations.RemoveField(
            model_name='magicmarket',
            name='ItemFK',
        ),
        migrations.RemoveField(
            model_name='magicmarket',
            name='ThiefFK',
        ),
        migrations.DeleteModel(
            name='CommonWares',
        ),
        migrations.DeleteModel(
            name='GuildAssets',
        ),
        migrations.DeleteModel(
            name='GuildRamp',
        ),
        migrations.DeleteModel(
            name='GuildTower',
        ),
        migrations.DeleteModel(
            name='MagicMarket',
        ),
    ]
