# Generated by Django 4.0.3 on 2024-01-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_guildstages_remove_guildassets_guildfk_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuildStages',
            new_name='GuildStage',
        ),
    ]
