# Generated by Django 4.0.3 on 2024-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_guild_lastheist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildstage',
            name='ObstaclesR1',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='ObstaclesR2',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='ObstaclesR3',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='ObstaclesR4',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='ObstaclesR5',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='RoomRewards',
        ),
        migrations.AddField(
            model_name='guildstage',
            name='LandingQueue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='LandingRewards',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='ObstaclesL1',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildstage',
            name='ObstaclesL2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='ObstaclesL3',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='ObstaclesL4',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='ObstaclesL5',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='Assignments',
            field=models.JSONField(null=True),
        ),
    ]
