# Generated by Django 4.0.3 on 2024-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_remove_guildstage_obstaclesr1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildstage',
            old_name='RoomTypes',
            new_name='LandingTypes',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='LandingQueue',
        ),
        migrations.AddField(
            model_name='guildstage',
            name='StageQueue',
            field=models.BooleanField(default=False),
        ),
    ]
