# Generated by Django 4.0.3 on 2024-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_rename_guildstages_guildstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildstage',
            old_name='TypeR1',
            new_name='Background',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='CompleteR1',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='CompleteR2',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='CompleteR3',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='CompleteR4',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='CompleteR5',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='TypeR2',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='TypeR3',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='TypeR4',
        ),
        migrations.RemoveField(
            model_name='guildstage',
            name='TypeR5',
        ),
        migrations.AddField(
            model_name='guildstage',
            name='BackgroundRoomBias',
            field=models.JSONField(default=[1]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildstage',
            name='CompleteRooms',
            field=models.JSONField(default=[0]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildstage',
            name='RoomTypes',
            field=models.JSONField(default=['o']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='ObstaclesR1',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='ObstaclesR2',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='ObstaclesR3',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='ObstaclesR4',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='guildstage',
            name='ObstaclesR5',
            field=models.JSONField(null=True),
        ),
    ]
