# Generated by Django 4.0.3 on 2024-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_rename_roomtypes_guildstage_landingtypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildstage',
            name='Actions',
            field=models.JSONField(null=True),
        ),
    ]
