# Generated by Django 4.0.3 on 2024-12-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_guildstage_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominguild',
            name='CooldownExpire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='roominguild',
            name='Status',
            field=models.TextField(default='Ready'),
        ),
        migrations.AddField(
            model_name='roominguild',
            name='UpgradeType',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
