# Generated by Django 4.0.3 on 2024-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_thiefinguild_wounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='CampaignWorld',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guild',
            name='StorageGems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='StorageGold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='StorageIron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='StorageStone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='StorageWood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='VaultIron',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='VaultStone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='VaultWood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guildstage',
            name='KeepLevel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
