# Generated by Django 4.0.3 on 2024-12-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_roominguild_cooldownexpire_roominguild_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='ThroneLevel',
        ),
        migrations.AlterField(
            model_name='roominguild',
            name='Level',
            field=models.IntegerField(default=0),
        ),
    ]
