# Generated by Django 4.0.3 on 2024-02-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_guild_campaignworld_guild_storagegems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildstage',
            name='Rewards',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
