# Generated by Django 4.0.3 on 2024-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_remove_guild_thronelevel_alter_roominguild_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominguild',
            name='Placement',
            field=models.TextField(),
        ),
    ]
