# Generated by Django 4.0.3 on 2024-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_rename_backgroundroombias_guildstage_backgroundbias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildstage',
            name='StageRewards',
            field=models.JSONField(null=True),
        ),
    ]
