# Generated by Django 4.0.3 on 2024-12-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_alter_roominguild_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='thiefinguild',
            name='TrainedSkills',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
