# Generated by Django 4.0.3 on 2024-02-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_alter_guildstage_stagerewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildstage',
            name='Assignments',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
