# Generated by Django 4.0.3 on 2024-12-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_thiefinguild_trainedskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thiefinguild',
            old_name='BasePower',
            new_name='PowerBase',
        ),
        migrations.AddField(
            model_name='thiefinguild',
            name='PowerLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thiefinguild',
            name='TrainedSkills',
            field=models.JSONField(default='[]'),
        ),
    ]
