# Generated by Django 4.0.3 on 2024-12-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_rename_basepower_thiefinguild_powerbase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thiefinguild',
            name='PowerLevel',
        ),
    ]
