# Generated by Django 4.0.3 on 2024-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_guildstage_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thiefinguild',
            old_name='Cooldown',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='thiefinguild',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='thiefinguild',
            name='Wounds',
        ),
        migrations.AddField(
            model_name='thiefinguild',
            name='CooldownExpire',
            field=models.DateTimeField(null=True),
        ),
    ]
