# Generated by Django 4.0.3 on 2025-01-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_remove_thiefinguild_powerlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominguild',
            name='StaffingData',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='thiefinguild',
            name='TrainedSkills',
            field=models.JSONField(default=list),
        ),
    ]
