# Generated by Django 4.0.3 on 2024-06-20 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_rename_cooldown_thiefinguild_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildstage',
            old_name='KeepLevel',
            new_name='ThroneLevel',
        ),
        migrations.CreateModel(
            name='GuildExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('Type', models.TextField()),
                ('Level', models.IntegerField()),
                ('Duration', models.TextField()),
                ('StartDate', models.DateTimeField(null=True)),
                ('Results', models.JSONField(null=True)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
                ('ThiefFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.thiefinguild')),
            ],
        ),
    ]
