# Generated by Django 4.0.3 on 2025-01-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_roominguild_staffingdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildstage',
            old_name='ThroneLevel',
            new_name='Level',
        ),
    ]
