# Generated by Django 4.0.3 on 2024-06-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_rename_keeplevel_guildstage_thronelevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='KeepLevel',
            new_name='ThroneLevel',
        ),
        migrations.AddField(
            model_name='guildexpedition',
            name='Claimed',
            field=models.BooleanField(default=False),
        ),
    ]
