# Generated by Django 4.0.3 on 2025-01-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_rename_thronelevel_guildstage_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketstore',
            old_name='ThroneLevel',
            new_name='Level',
        ),
    ]
