# Generated by Django 4.0.3 on 2024-06-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_rename_keeplevel_guild_thronelevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildexpedition',
            old_name='Type',
            new_name='BaseType',
        ),
        migrations.AddField(
            model_name='guildexpedition',
            name='FullType',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
