# Generated by Django 4.0.3 on 2024-07-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_rename_type_guildexpedition_basetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='MaxThieves',
            field=models.IntegerField(default=6),
        ),
    ]
