# Generated by Django 4.0.3 on 2025-01-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_rename_thronelevel_marketstore_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildstage',
            name='Burgles',
            field=models.JSONField(null=True),
        ),
    ]
