# Generated by Django 4.0.3 on 2024-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_guild_maxthieves'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminguild',
            name='ResourceId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thiefinguild',
            name='ResourceId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
