# Generated by Django 4.0.3 on 2025-01-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_rename_thronelevel_marketstore_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketstore',
            old_name='Level',
            new_name='World',
        ),
    ]
