# Generated by Django 4.0.3 on 2025-01-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_rename_level_marketstore_world'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildstage',
            old_name='Level',
            new_name='World',
        ),
    ]
