# Generated by Django 4.0.3 on 2024-07-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_iteminguild_resourceid_thiefinguild_resourceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminguild',
            name='ResourceId',
        ),
        migrations.RemoveField(
            model_name='thiefinguild',
            name='ResourceId',
        ),
    ]
