# Generated by Django 4.0.3 on 2024-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_remove_iteminguild_resourceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildexpedition',
            name='SlotNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
