# Generated by Django 4.0.3 on 2025-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_rename_level_guildstage_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='CreateDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guild',
            name='LastPlayed',
            field=models.DateField(),
        ),
    ]
