# Generated by Django 4.0.3 on 2024-07-28 01:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_guild_dungeoncheck_alter_guild_vaultgems'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(default=django.utils.timezone.now)),
                ('ThroneLevel', models.IntegerField()),
                ('ResourceId', models.TextField()),
                ('RareProperties', models.JSONField(null=True)),
                ('Bought', models.BooleanField(default=False)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
    ]
