# Generated by Django 4.0.3 on 2024-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_marketstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstore',
            name='StoreType',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
    ]
