# Generated by Django 4.0.3 on 2024-09-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_marketstore_storetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Description', models.TextField(null=True)),
                ('Level', models.IntegerField()),
                ('Placement', models.TextField(unique=True)),
                ('GuildFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.guild')),
            ],
        ),
    ]
