# Generated by Django 4.0.3 on 2024-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_roominguild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='MaxThieves',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='StorageGems',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='StorageGold',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='StorageIron',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='StorageStone',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='StorageWood',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='TotalPower',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='VaultIron',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='VaultWood',
        ),
    ]
