# Generated by Django 4.0.3 on 2023-12-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeepUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('Wood', models.IntegerField()),
                ('Stone', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('UpgradePeriod', models.TextField()),
                ('MaxRoomCount', models.IntegerField()),
                ('MaxRoomLevel', models.IntegerField()),
                ('MaxThieves', models.IntegerField()),
                ('GoldStorage', models.IntegerField(null=True)),
                ('GemStorage', models.IntegerField(null=True)),
                ('WoodStorage', models.IntegerField(null=True)),
                ('StoneStorage', models.IntegerField(null=True)),
                ('IronStorage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThiefLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('Experience', models.IntegerField()),
                ('Power', models.IntegerField()),
                ('TrainPeriod', models.TextField()),
                ('WoundPeriod', models.TextField()),
                ('KnockedOutPeriod', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UnlockableThief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.TextField()),
                ('Stars', models.IntegerField()),
                ('UnlockKeep', models.IntegerField()),
                ('StoreCost', models.IntegerField(null=True)),
                ('UnlockCost', models.IntegerField(null=True)),
                ('StartTrait', models.TextField()),
                ('RandomTraits', models.TextField()),
            ],
            options={
                'unique_together': {('Class', 'Stars')},
            },
        ),
        migrations.CreateModel(
            name='UnlockableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Level', models.IntegerField()),
                ('Magic', models.IntegerField()),
                ('Points', models.IntegerField()),
                ('Slot', models.TextField()),
                ('StoreCost', models.IntegerField(null=True)),
                ('UnlockCost', models.IntegerField(null=True)),
                ('Requirement', models.TextField(null=True)),
                ('Trait', models.TextField(null=True)),
                ('Combat', models.TextField(null=True)),
                ('Skill', models.TextField(null=True)),
                ('MagicBonus', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('Name', 'Level', 'Points')},
            },
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Name', models.TextField()),
                ('Trait', models.TextField()),
                ('Skill', models.TextField()),
                ('Success', models.TextField()),
                ('Failure', models.TextField()),
                ('Experience', models.IntegerField()),
                ('Difficulty', models.IntegerField()),
                ('Damage', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('Level', 'Name')},
            },
        ),
        migrations.CreateModel(
            name='TestRamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('ObstaclesR1', models.IntegerField(null=True)),
                ('LevelR1', models.IntegerField(null=True)),
                ('Gold', models.IntegerField(null=True)),
                ('Gems', models.IntegerField(null=True)),
                ('Wood', models.IntegerField(null=True)),
                ('Stone', models.IntegerField(null=True)),
                ('Iron', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('World', 'StageNo')},
            },
        ),
        migrations.CreateModel(
            name='GothicTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('ObstaclesR1', models.IntegerField(null=True)),
                ('LevelR1', models.IntegerField(null=True)),
                ('ObstaclesR2', models.IntegerField(null=True)),
                ('LevelR2', models.IntegerField(null=True)),
                ('ObstaclesR3', models.IntegerField(null=True)),
                ('LevelR3', models.IntegerField(null=True)),
                ('Gold', models.IntegerField(null=True)),
                ('Gems', models.IntegerField(null=True)),
                ('Wood', models.IntegerField(null=True)),
                ('Stone', models.IntegerField(null=True)),
                ('Iron', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('World', 'StageNo')},
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Name', models.TextField()),
                ('Trait', models.TextField()),
                ('Skill', models.TextField()),
                ('Success', models.TextField()),
                ('Failure', models.TextField()),
                ('Experience', models.IntegerField()),
                ('Attack', models.IntegerField()),
                ('Damage', models.IntegerField()),
                ('Defense', models.IntegerField()),
                ('Health', models.IntegerField()),
            ],
            options={
                'unique_together': {('Level', 'Name')},
            },
        ),
    ]
