# Generated by Django 4.0.3 on 2023-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('Wood', models.IntegerField()),
                ('Stone', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('UpgradePeriod', models.TextField()),
                ('BonusGold', models.TextField()),
                ('DailySlots', models.IntegerField()),
                ('FenceStaff', models.IntegerField()),
                ('BonusGems', models.TextField()),
                ('UnlockSlots', models.IntegerField()),
                ('JewelerStaff', models.IntegerField()),
                ('BonusMaterials', models.TextField()),
                ('WorkshopStaff', models.IntegerField()),
                ('BonusXP', models.TextField()),
                ('ReformatoryStaff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingletonUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('Wood', models.IntegerField()),
                ('Stone', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('UpgradePeriod', models.TextField()),
                ('KeepDefense', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageUpgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('Wood', models.IntegerField()),
                ('Stone', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('UpgradePeriod', models.TextField()),
                ('MaxThief', models.IntegerField()),
                ('RecoveryBonus', models.TextField()),
                ('GoldStorage', models.IntegerField()),
                ('GemStorage', models.IntegerField()),
                ('WoodStorage', models.IntegerField()),
                ('StoneStorage', models.IntegerField()),
                ('IronStorage', models.IntegerField()),
                ('MaxThiefLevel', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='keepupgrades',
            name='GemStorage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keepupgrades',
            name='GoldStorage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keepupgrades',
            name='IronStorage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keepupgrades',
            name='StoneStorage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keepupgrades',
            name='WoodStorage',
            field=models.IntegerField(),
        ),
    ]
