# Generated by Django 4.0.3 on 2024-06-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField()),
                ('MainTrait', models.TextField()),
                ('SecondaryOne', models.TextField()),
                ('SecondaryTwo', models.TextField()),
                ('SecondaryThree', models.TextField()),
                ('SkillOne', models.TextField()),
                ('SkillTwo', models.TextField()),
                ('SkillThree', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='KeepUpgrades',
            new_name='ThroneUpgrades',
        ),
    ]
