# Generated by Django 4.0.3 on 2024-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0002_throneroom_magicslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World', models.IntegerField()),
                ('Level', models.IntegerField()),
                ('Obstacles', models.IntegerField()),
                ('RequiredPower', models.IntegerField()),
            ],
        ),
    ]
