# Generated by Django 4.0.3 on 2023-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0002_factoryupgrades_singletonupgrades_storageupgrades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('ObstaclesR1', models.IntegerField(null=True)),
                ('LevelR1', models.IntegerField(null=True)),
                ('ObstaclesR2', models.IntegerField(null=True)),
                ('LevelR2', models.IntegerField(null=True)),
                ('ObstaclesR3', models.IntegerField(null=True)),
                ('LevelR3', models.IntegerField(null=True)),
                ('ObstaclesR4', models.IntegerField(null=True)),
                ('LevelR4', models.IntegerField(null=True)),
                ('ObstaclesR5', models.IntegerField(null=True)),
                ('LevelR5', models.IntegerField(null=True)),
                ('Gold', models.IntegerField(null=True)),
                ('Gems', models.IntegerField(null=True)),
                ('Wood', models.IntegerField(null=True)),
                ('Stone', models.IntegerField(null=True)),
                ('Iron', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('World', 'StageNo')},
            },
        ),
        migrations.CreateModel(
            name='LeagueTrials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keep', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('ObstaclesR1', models.IntegerField(null=True)),
                ('LevelR1', models.IntegerField(null=True)),
                ('ObstaclesR2', models.IntegerField(null=True)),
                ('LevelR2', models.IntegerField(null=True)),
                ('ObstaclesR3', models.IntegerField(null=True)),
                ('LevelR3', models.IntegerField(null=True)),
                ('ObstaclesR4', models.IntegerField(null=True)),
                ('LevelR4', models.IntegerField(null=True)),
                ('ObstaclesR5', models.IntegerField(null=True)),
                ('LevelR5', models.IntegerField(null=True)),
                ('Gold', models.IntegerField(null=True)),
                ('Gems', models.IntegerField(null=True)),
                ('Wood', models.IntegerField(null=True)),
                ('Stone', models.IntegerField(null=True)),
                ('Iron', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('Keep', 'StageNo')},
            },
        ),
        migrations.CreateModel(
            name='TrialDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekDay', models.TextField()),
                ('StageType', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestRamp',
        ),
        migrations.RenameField(
            model_name='gothictower',
            old_name='World',
            new_name='Keep',
        ),
        migrations.AlterUniqueTogether(
            name='gothictower',
            unique_together={('Keep', 'StageNo')},
        ),
        migrations.AddField(
            model_name='gothictower',
            name='LevelR4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gothictower',
            name='LevelR5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gothictower',
            name='ObstaclesR4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gothictower',
            name='ObstaclesR5',
            field=models.IntegerField(null=True),
        ),
    ]
