# Generated by Django 4.0.3 on 2024-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0002_expedition_rename_keepupgrades_throneupgrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World', models.IntegerField()),
                ('Level', models.IntegerField()),
                ('Duration', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Expedition',
            new_name='ExpeditionType',
        ),
    ]
