# Generated by Django 4.0.3 on 2024-06-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0003_expeditionlevel_rename_expedition_expeditiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlockablethief',
            old_name='UnlockKeep',
            new_name='UnlockThrone',
        ),
        migrations.RemoveField(
            model_name='unlockableitem',
            name='UnlockCost',
        ),
        migrations.RemoveField(
            model_name='unlockablethief',
            name='UnlockCost',
        ),
    ]
