# Generated by Django 4.0.3 on 2023-12-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0003_campaign_leaguetrials_trialdays_delete_testramp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueTrials',
            new_name='LeagueTrial',
        ),
        migrations.RenameModel(
            old_name='TrialDays',
            new_name='TrialDay',
        ),
    ]
