# Generated by Django 4.0.3 on 2023-12-10 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0004_rename_leaguetrials_leaguetrial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unlockableitem',
            old_name='MagicBonus',
            new_name='Enchantments',
        ),
    ]
