# Generated by Django 4.0.3 on 2024-12-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0004_rename_levelr1_campaign_levellnd1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomupgrade',
            old_name='Period_Advan',
            new_name='Period_Advanced',
        ),
        migrations.RenameField(
            model_name='roomupgrade',
            old_name='Period_Throne',
            new_name='Period_Unique',
        ),
        migrations.RenameField(
            model_name='roomupgrade',
            old_name='Stone_Advan',
            new_name='Stone_Advanced',
        ),
        migrations.RenameField(
            model_name='roomupgrade',
            old_name='Stone_Throne',
            new_name='Stone_Unique',
        ),
        migrations.AddField(
            model_name='castleroom',
            name='UpgradeType',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
