# Generated by Django 4.0.3 on 2024-06-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0004_rename_unlockkeep_unlockablethief_unlockthrone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expeditionlevel',
            old_name='World',
            new_name='Throne',
        ),
        migrations.RenameField(
            model_name='gothictower',
            old_name='Keep',
            new_name='Throne',
        ),
        migrations.RenameField(
            model_name='leaguetrial',
            old_name='Keep',
            new_name='Throne',
        ),
        migrations.RenameField(
            model_name='singletonupgrades',
            old_name='KeepDefense',
            new_name='ThroneDefense',
        ),
        migrations.AddField(
            model_name='enemy',
            name='World',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trap',
            name='World',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gothictower',
            unique_together={('Throne', 'StageNo')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguetrial',
            unique_together={('Throne', 'StageNo')},
        ),
    ]
