# Generated by Django 4.0.3 on 2024-12-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0005_rename_period_advan_roomupgrade_period_advanced_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(unique=True)),
                ('MaxRoomCount', models.IntegerField()),
                ('MaxRoomLevel', models.IntegerField()),
                ('Throne_Gold', models.IntegerField()),
                ('Throne_Stone', models.IntegerField()),
                ('Hall_MaxThieves', models.IntegerField()),
                ('Hall_MagicStore', models.IntegerField()),
                ('Hall_Expedition', models.IntegerField()),
                ('Keep_Defenders', models.IntegerField()),
                ('Keep_Traps', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ThroneRoom',
        ),
        migrations.RemoveField(
            model_name='basicroom',
            name='Keep_Defenders',
        ),
        migrations.RemoveField(
            model_name='basicroom',
            name='Keep_Traps',
        ),
    ]
