# Generated by Django 4.0.3 on 2024-06-30 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0005_rename_world_expeditionlevel_throne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singletonupgrades',
            old_name='ThroneDefense',
            new_name='KeepDefense',
        ),
    ]
