# Generated by Django 4.0.3 on 2024-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0006_rename_thronedefense_singletonupgrades_keepdefense'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockableitem',
            name='ResourceId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlockablethief',
            name='ResourceId',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
