# Generated by Django 4.0.3 on 2025-01-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0006_uniqueroom_delete_throneroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castleroom',
            old_name='UnlockThrone',
            new_name='UnlockLevel',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='Throne',
            new_name='World',
        ),
        migrations.RenameField(
            model_name='expeditionlevel',
            old_name='Throne',
            new_name='World',
        ),
        migrations.RenameField(
            model_name='gothictower',
            old_name='Throne',
            new_name='World',
        ),
        migrations.RenameField(
            model_name='leaguetrial',
            old_name='Throne',
            new_name='World',
        ),
        migrations.RenameField(
            model_name='unlockableitem',
            old_name='Throne',
            new_name='UnlockLevel',
        ),
        migrations.RenameField(
            model_name='unlockablethief',
            old_name='UnlockThrone',
            new_name='UnlockLevel',
        ),
        migrations.AlterUniqueTogether(
            name='dungeon',
            unique_together={('World', 'StageNo')},
        ),
        migrations.AlterUniqueTogether(
            name='gothictower',
            unique_together={('World', 'StageNo')},
        ),
        migrations.AlterUniqueTogether(
            name='leaguetrial',
            unique_together={('World', 'StageNo')},
        ),
    ]
