# Generated by Django 4.0.3 on 2024-07-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0007_unlockableitem_resourceid_unlockablethief_resourceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Throne', models.IntegerField()),
                ('StageNo', models.IntegerField()),
                ('ObstaclesR1', models.IntegerField(null=True)),
                ('LevelR1', models.IntegerField(null=True)),
                ('ObstaclesR2', models.IntegerField(null=True)),
                ('LevelR2', models.IntegerField(null=True)),
                ('ObstaclesR3', models.IntegerField(null=True)),
                ('LevelR3', models.IntegerField(null=True)),
                ('ObstaclesR4', models.IntegerField(null=True)),
                ('LevelR4', models.IntegerField(null=True)),
                ('ObstaclesR5', models.IntegerField(null=True)),
                ('LevelR5', models.IntegerField(null=True)),
                ('Gold', models.IntegerField(null=True)),
                ('Gems', models.IntegerField(null=True)),
                ('Wood', models.IntegerField(null=True)),
                ('Stone', models.IntegerField(null=True)),
                ('Iron', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('Throne', 'StageNo')},
            },
        ),
    ]
