# Generated by Django 4.0.3 on 2025-01-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0007_rename_unlockthrone_castleroom_unlocklevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Iron',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='Wood',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='Iron',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='Wood',
        ),
        migrations.RemoveField(
            model_name='gothictower',
            name='Iron',
        ),
        migrations.RemoveField(
            model_name='gothictower',
            name='Wood',
        ),
        migrations.RemoveField(
            model_name='leaguetrial',
            name='Iron',
        ),
        migrations.RemoveField(
            model_name='leaguetrial',
            name='Wood',
        ),
    ]
