# Generated by Django 4.0.3 on 2024-07-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0008_dungeon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockablethief',
            name='RandomTraits',
            field=models.IntegerField(),
        ),
    ]
