# Generated by Django 4.0.3 on 2025-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0008_remove_campaign_iron_remove_campaign_wood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicroom',
            old_name='Cartog_Recovery',
            new_name='Cartog_Bonus',
        ),
    ]
