# Generated by Django 4.0.3 on 2025-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0009_rename_cartog_recovery_basicroom_cartog_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicroom',
            name='Cartog_MinDur',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
