# Generated by Django 4.0.3 on 2025-01-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0010_basicroom_cartog_mindur'),
    ]

    operations = [
        migrations.AddField(
            model_name='expeditionlevel',
            name='DurationMin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
