# Generated by Django 4.0.3 on 2024-09-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0010_advancedroom_basicroom_castleroom_roomupgrade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockableitem',
            name='Throne',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
