# Generated by Django 4.0.3 on 2025-01-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0011_expeditionlevel_durationmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicroom',
            name='Cartog_MinDur',
        ),
    ]
