# Generated by Django 4.0.3 on 2024-09-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0011_unlockableitem_throne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedroom',
            name='Workshop_Defense',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='castleroom',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
