# Generated by Django 4.0.3 on 2025-01-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0012_remove_basicroom_cartog_mindur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thieflevel',
            old_name='KnockedOutPeriod',
            new_name='BeatenPeriod',
        ),
        migrations.AddField(
            model_name='thieflevel',
            name='BeatenPeriodMin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thieflevel',
            name='WoundPeriodMin',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
