# Generated by Django 4.0.3 on 2025-02-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0013_rename_knockedoutperiod_thieflevel_beatenperiod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='LevelLnd1',
            new_name='DifficultyL1',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='LevelLnd2',
            new_name='DifficultyL2',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='LevelLnd3',
            new_name='DifficultyL3',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='LevelLnd4',
            new_name='DifficultyL4',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='LevelLnd5',
            new_name='DifficultyL5',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='LevelLnd1',
            new_name='DifficultyL1',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='LevelLnd2',
            new_name='DifficultyL2',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='LevelLnd3',
            new_name='DifficultyL3',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='LevelLnd4',
            new_name='DifficultyL4',
        ),
        migrations.RenameField(
            model_name='dungeon',
            old_name='LevelLnd5',
            new_name='DifficultyL5',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ObstaclesL1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ObstaclesL2',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ObstaclesL3',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ObstaclesL4',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ObstaclesL5',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='ObstaclesL1',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='ObstaclesL2',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='ObstaclesL3',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='ObstaclesL4',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='ObstaclesL5',
        ),
    ]
