# Generated by Django 4.0.3 on 2025-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emporium', '0014_rename_levellnd1_campaign_difficultyl1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='DifficultyL1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DifficultyL2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DifficultyL3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DifficultyL4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='DifficultyL5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='DifficultyL1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='DifficultyL2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='DifficultyL3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='DifficultyL4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='DifficultyL5',
            field=models.TextField(null=True),
        ),
    ]
